### ISSUE TITLE
Run `git gc --aggressive`

### ISSUE THREAD

**Issue by brettcannon** [orsenthil/cpython-hg-to-git#2]
It was pointed out to me that the peps repo wasn't compacted and so it's 34MB instead of 8MB. Running GC before pushing should be done to make sure repos are as small as possible.

**Comment by orsenthil** [comment]
We do run it as part of the migrate: https://github.com/orsenthil/cpython-hg-to-git/blob/master/hg_git_migrator.py#L117 

Is it required to run multiple times? (I will investigate that).

**Comment by brettcannon** [comment]
Not sure. I just know that @birkenfeld pointed out that running it locally on his machine led to a smaller repo.

**Comment by fgregg** [comment]
It appears that github runs `git gc --agressive` periodically on their repos. http://stackoverflow.com/questions/9135095/git-gc-aggressive-push-to-server
