### ISSUE TITLE
Edge cases

### ISSUE THREAD

**Issue by Carreau** [orsenthil/cpython-hg-to-git#3]
```
[cfcc45f18515]: Refer reader to platform library docs for specific semantics.

Resolves SF bugs 697989, 697988, 697986.
[cfcc45f18515]: Refer reader to platform library docs for specific semantics.

Resolves SF bpo-697989, 697988, 697986.
````

Should it convert the 3 numbers to bpo- ?

Though I think the texts of this form are really are, so might not be worth it.

**Comment by orsenthil** [comment]
Thanks for the report. We had solved this, but we decided not to rewrite commit messages..
