### ISSUE TITLE
Documentation: mention https://bitbucket.org/orsenthil/hg-git

### ISSUE THREAD

**Issue by akruis** [orsenthil/cpython-hg-to-git#4]
Hi Senthil,

many thanks for your excellent documentation of the hg to git migration. Today I was able to successfully migrate Stackless Python from hg to git following your instructions. May I propose a single addition to your documentation: please mention that one must use your patched version of hg-git (at https://bitbucket.org/orsenthil/hg-git).

Kind regards,
  Anselm

**Comment by orsenthil** [comment]
Thanks for your kind words, @akruis  - I updated the README.
